minima: sherry-lai
author: sherry lai
email: sherrylai9420@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  bible bullet journal & blogz 

# social links
twitter_username: sherrylayschips # DO NOT include the @ character, or else the build will fail!
github_username:  sherry-lai # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
